
function ressourceHandler_loadAudioFiles()
   
    
end

function ressourceHandler_loadTiles()
    
    -- tut files
    tut_mouse = love.graphics.newImage("res/mouse.png")
    tut_build = love.graphics.newImage("res/build.png")
    tut_ressources = love.graphics.newImage("res/ressources.png")
    tut_layer = love.graphics.newImage("res/layer.png")
    
    tileset = {}
    
    local tileSource = love.image.newImageData("res/tileset.png")
    
    local imgData = love.image.newImageData(tilesize, tilesize)
    
    -- grass
    imgData:paste(tileSource, 0, 0, 0, 0, tilesize, tilesize)
    tileset["grass1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 1 * tilesize, 0, tilesize, tilesize)
    tileset["grass2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 2 * tilesize, 0, tilesize, tilesize)
    tileset["grass3"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 3 * tilesize, 0, tilesize, tilesize)
    tileset["grass4"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 4 * tilesize, 0, tilesize, tilesize)
    tileset["grass5"] = love.graphics.newImage(imgData)
    
    
    -- grass edges
    imgData:paste(tileSource, 0, 0, 8 * tilesize, 0, tilesize, tilesize)
    tileset["grass_edge_u"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 7 * tilesize, 1 * tilesize, tilesize, tilesize)
    tileset["grass_edge_l"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 9 * tilesize, 1 * tilesize, tilesize, tilesize)
    tileset["grass_edge_r"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 8 * tilesize, 2 * tilesize, tilesize, tilesize)
    tileset["grass_edge_d"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 7 * tilesize, 0, tilesize, tilesize)
    tileset["grass_edge_lu"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 7 * tilesize, 2 * tilesize, tilesize, tilesize)
    tileset["grass_edge_ld"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 9 * tilesize, 2 * tilesize, tilesize, tilesize)
    tileset["grass_edge_rd"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 9 * tilesize, 0, tilesize, tilesize)
    tileset["grass_edge_ru"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 9 * tilesize, 4 * tilesize, tilesize, tilesize)
    tileset["grass_inner_rd"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 8 * tilesize, 4 * tilesize, tilesize, tilesize)
    tileset["grass_inner_ld"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 9 * tilesize, 3 * tilesize, tilesize, tilesize)
    tileset["grass_inner_ru"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 8 * tilesize, 3 * tilesize, tilesize, tilesize)
    tileset["grass_inner_lu"] = love.graphics.newImage(imgData)
    
    -- ressources
    imgData:paste(tileSource, 0, 0, 0, 4 * tilesize, tilesize, tilesize)
    tileset["tree1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 1 * tilesize, 4 * tilesize, tilesize, tilesize)
    tileset["tree2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 2 * tilesize, 4 * tilesize, tilesize, tilesize)
    tileset["tree_down"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 3 * tilesize, 4 * tilesize, tilesize, tilesize)
    tileset["stump"] = love.graphics.newImage(imgData)
    
    --cliff
    imgData:paste(tileSource, 0, 0, 0, 1 * tilesize, tilesize, tilesize)
    tileset["cliff1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 1 * tilesize, 1 * tilesize, tilesize, tilesize)
    tileset["cliff2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 2 * tilesize, 1 * tilesize, tilesize, tilesize)
    tileset["cliff3"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 3 * tilesize, 1 * tilesize, tilesize, tilesize)
    tileset["cliff4"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 0, 2 * tilesize, tilesize, tilesize)
    tileset["cliff_edge_l1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 0, 3 * tilesize, tilesize, tilesize)
    tileset["cliff_edge_l2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, tilesize, 2 * tilesize, tilesize, tilesize)
    tileset["cliff_edge_r1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, tilesize, 3 * tilesize, tilesize, tilesize)
    tileset["cliff_edge_r2"] = love.graphics.newImage(imgData)
    
    -- "rock" sort of terrain
    imgData:paste(tileSource, 0, 0, 9 * tilesize , 1 * tilesize, tilesize, tilesize)
    tileset["rock"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 3 * tilesize, tilesize, tilesize, tilesize)
    
    
    -- ressources that can lie around
    imgData:paste(tileSource, 0, 0, 2 * tilesize, 3 * tilesize, tilesize, tilesize)
    tileset["build_planks1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 3 * tilesize, 3 * tilesize, tilesize, tilesize)
    tileset["build_planks2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 4 * tilesize, 3 * tilesize, tilesize, tilesize)
    tileset["build_planks3"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 5 * tilesize, 3 * tilesize, tilesize, tilesize)
    tileset["build_planks4"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 4 * tilesize, 4 * tilesize, tilesize, tilesize)
    tileset["build_log1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 5 * tilesize, 4 * tilesize, tilesize, tilesize)
    tileset["build_log2"] = love.graphics.newImage(imgData)
    
    -- buildings
    imgData:paste(tileSource, 0, 0, 2 * tilesize, 2 * tilesize, tilesize, tilesize)
    tileset["hut_ground"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 3 * tilesize, 2 * tilesize, tilesize, tilesize)
    tileset["hut_frame"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 4 * tilesize, 2 * tilesize, tilesize, tilesize)
    tileset["hut"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 0, 5 * tilesize, tilesize, tilesize)
    tileset["woodcutter_ground"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 1 * tilesize, 5 * tilesize, tilesize, tilesize)
    tileset["woodcutter_frame"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 2 * tilesize, 5 * tilesize, tilesize, tilesize)
    tileset["woodcutter"] = love.graphics.newImage(imgData)
    
    -- waterfall
    imgData:paste(tileSource, 0, 0, 6 * tilesize, 5 * tilesize, tilesize, tilesize)
    tileset["waterfall_basel"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 7 * tilesize, 5 * tilesize, tilesize, tilesize)
    tileset["waterfall_baser"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 8 * tilesize, 5 * tilesize, tilesize, tilesize)
    tileset["waterfall_l1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 8 * tilesize, 6 * tilesize, tilesize, tilesize)
    tileset["waterfall_l2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 8 * tilesize, 7 * tilesize, tilesize, tilesize)
    tileset["waterfall_l3"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 9 * tilesize, 5 * tilesize, tilesize, tilesize)
    tileset["waterfall_r1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 9 * tilesize, 6 * tilesize, tilesize, tilesize)
    tileset["waterfall_r2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 9 * tilesize, 7 * tilesize, tilesize, tilesize)
    tileset["waterfall_r3"] = love.graphics.newImage(imgData)
    
    --icons
    imgData:paste(tileSource, 0, 0, 0, 9 * tilesize, tilesize, tilesize)
    tileset["log"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 1 * tilesize, 9 * tilesize, tilesize, tilesize)
    tileset["planks"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 2 * tilesize, 9 * tilesize, tilesize, tilesize)
    tileset["stone"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 3 * tilesize, 9 * tilesize, tilesize, tilesize)
    tileset["iron"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 4 * tilesize, 9 * tilesize, tilesize, tilesize)
    tileset["gold"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 1 * tilesize, 8 * tilesize, tilesize, tilesize)
    tileset["arrow_up"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 2 * tilesize, 8 * tilesize, tilesize, tilesize)
    tileset["arrow_down"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 0, 8 * tilesize, tilesize, tilesize)
    tileset["rectangle"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 3 * tilesize, 8 * tilesize, tilesize, tilesize)
    tileset["x"] = love.graphics.newImage(imgData)
    
    
    charset = {}
    tileSource = love.image.newImageData("res/villager.png")
    imgData = love.image.newImageData(8, 12)
    imgData:paste(tileSource, 0, 0, 0, 0, 8, 12)
    charset["idle1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 8, 0, 8, 12)
    charset["idle2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 16, 0, 8, 12)
    charset["idle3"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 24, 0, 8, 12)
    charset["idle4"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 0, 12, 8, 12)
    charset["right1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 8, 12, 8, 12)
    charset["right2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 16, 12, 8, 12)
    charset["right3"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 24, 12, 8, 12)
    charset["right4"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 0, 24, 8, 12)
    charset["left1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 8, 24, 8, 12)
    charset["left2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 16, 24, 8, 12)
    charset["left3"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 24, 24, 8, 12)
    charset["left4"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 0, 36, 8, 12)
    charset["work1"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 8, 36, 8, 12)
    charset["work2"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 16, 36, 8, 12)
    charset["work3"] = love.graphics.newImage(imgData)
    imgData:paste(tileSource, 0, 0, 24, 36, 8, 12)
    charset["work4"] = love.graphics.newImage(imgData)
    
end